import{a as v,S as E,i as u}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const w="48874929-f90ec9beeb99fdbae3d7d9b25",S="https://pixabay.com/api/";async function m(r,o=1,l=40){try{const s=await v.get(S,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:l}});if(s.data.hits.length===0)throw new Error("No images found for the given query");return{hits:s.data.hits,totalHits:s.data.totalHits}}catch(s){return console.error("Error fetching images:",s.message||s),[]}}function f(r){const o=document.querySelector(".gallery"),l=r.map(({webformatURL:e,largeImageURL:t,tags:c,likes:h,views:b,comments:L,downloads:q})=>`
      <div class="gallery-item">
        <a href="${t}" class="gallery-link">
          <img src="${e}" alt="${c}" class="gallery-image" />
        </a>
        <div class="info">
          <p>❤️ ${h}</p>
          <p>👀 ${b}</p>
          <p>💬 ${L}</p>
          <p>⬇️ ${q}</p>
        </div>
      </div>`).join("");o.insertAdjacentHTML("beforeend",l),new E(".gallery a").refresh()}const P=document.querySelector("#search-form"),x=document.querySelector("#search-input"),n=document.querySelector(".loader"),y=document.querySelector(".gallery"),a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more");a.style.display="none";document.body.appendChild(a);y.style.display="grid";y.style.gridTemplateColumns="repeat(3, 1fr)";y.style.gap="10px";y.querySelectorAll(".gallery-image").forEach(r=>{r.style.width="100%",r.style.height="auto"});let p="",i=1,g=0;const d=40;P.addEventListener("submit",async r=>{if(r.preventDefault(),p=x.value.trim(),i=1,!p){u.error({title:"Error",message:"Please enter a search query!"});return}y.innerHTML="",n.style.display="block",a.style.display="none";try{const{hits:o,totalHits:l}=await m(p,i,d);g=l,n.style.display="none",o.length===0?u.warning({title:"No Results",message:"No images found. Try again!"}):(f(o),g>d&&(a.style.display="block"))}catch{n.style.display="none",u.error({title:"Error",message:"Failed to load images. Please try again later."})}});a.addEventListener("click",async()=>{if(i*d<g){i++,n.style.display="block";try{const{hits:r}=await m(p,i,d);f(r),n.style.display="none",window.scrollBy({top:document.querySelector(".gallery").getBoundingClientRect().height*2,behavior:"smooth"}),i*d>=g&&(a.style.display="none")}catch{n.style.display="none",u.error({title:"Error",message:"Failed to load images. Please try again later."})}}});
//# sourceMappingURL=index.js.map
