import{a as L,S as v,i as y}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const q="48874929-f90ec9beeb99fdbae3d7d9b25",S="https://pixabay.com/api/";async function p(r,o=1,i=40){try{return(await L.get(S,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i}})).data.hits}catch(n){return console.error("Error fetching images:",n),[]}}function g(r){const o=document.querySelector(".gallery");o.innerHTML=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:l,views:f,comments:h,downloads:b})=>`
      <div class="gallery-item">
        <a href="${e}" class="gallery-link">
          <img src="${n}" alt="${t}" class="gallery-image" />
        </a>
        <div class="info">
          <p>❤️ ${l}</p>
          <p>👀 ${f}</p>
          <p>💬 ${h}</p>
          <p>⬇️ ${b}</p>
        </div>
      </div>`).join(""),new v(".gallery a").refresh()}const E=document.querySelector("#search-form"),w=document.querySelector("#search-input"),d=document.querySelector(".loader"),a=document.querySelector(".gallery"),s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more");s.style.display="none";document.body.appendChild(s);a.style.display="grid";a.style.gridTemplateColumns="repeat(3, 1fr)";a.style.gap="10px";a.querySelectorAll(".gallery-image").forEach(r=>{r.style.width="100%",r.style.height="auto"});let c="",u=1;const m=40;E.addEventListener("submit",async r=>{if(r.preventDefault(),c=w.value.trim(),u=1,!c){y.error({title:"Error",message:"Please enter a search query!"});return}a.innerHTML="",d.style.display="block",s.style.display="none";const o=await p(c,u,m);d.style.display="none",o.length===0?y.warning({title:"No Results",message:"No images found. Try again!"}):(g(o),s.style.display="block")});s.addEventListener("click",async()=>{u++,d.style.display="block";const r=await p(c,u,m);if(d.style.display="none",r.length===0){s.style.display="none",y.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."});return}g(r);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
